### PR TITLE
Tidy up schema definitions for Postgres tables

### LINKED ISSUE #728: Create 3 new indexes with SQLAlchemy
Now that we've got a high volume database, we can start addressing bottlenecks.

Here are indexes to get around the first bottlenecks:
```
CREATE INDEX "idx_states_comp_sensor_source" ON pepys."States" (sensor_id, source_id);
CREATE INDEX "idx_contacts_comp_sensor_source" ON pepys."Contacts" (sensor_id, source_id);
CREATE INDEX "idx_comments_comp_platform_source" ON pepys."Comments" (platform_id, source_id);
```
I guess we need to create them in Alembic, so the server gets updated with the next update.

### PR DESCRIPTION
**Pull request by BarisSari**
## 🧰 Issue
~~Fixes #728 .~~

## 🚀 Overview: 
~~I added indexes to the related classes in `sqlite_db.py` and `postgres_db.py`. Then, I created Alembic files for database migration.~~

## 🔨Work carried out:
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

## 📝 Developer Notes:
I've made a change for Postgres tables. We were giving `schema: "pepys"` for each Table. Instead, I added `schema` parameter to inherited Metadata (`meta_postgres`). It doesn't affect anything at all but I believe it's tidier now.

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @BarisSari - does this PR also cover the attempt to try to remove the need to include the "Pepys" schema name when entering SQL?

Did it work? Do we do something different now?

**Comment by BarisSari** [comment]
> Hello @BarisSari - does this PR also cover the attempt to try to remove the need to include the "Pepys" schema name when entering SQL?
> 
> Did it work? Do we do something different now?

Hello @IanMayo. No, I didn't try to cover that task. I realised that we had many unnecessary lines in your Postgres table definitions. I removed them but we still have the same "pepys" schema.

**Comment by robintw** [comment]
@IanMayo Just reviewing this, and wanted to check about the indexes that you asked us to create in the original issue. The `ON pepys."States" (sensor_id, source_id);` bit means the index is a joint index, and so I think it will only work if we search by `sensor_id = X` or `sensor_id = X and source_id = Y` but *not* searching on just `source_id = X`.

Is this what we want?

(I'm not an expert on indexes, but [this page](https://www.postgresqltutorial.com/postgresql-indexes/postgresql-multicolumn-indexes/) seems to match my understanding.)

**Comment by IanMayo** [comment]
Thanks @robintw  - question posted to DB developer.

**Comment by IanMayo** [comment]
> > Hello @BarisSari - does this PR also cover the attempt to try to remove the need to include the "Pepys" schema name when entering SQL?
> > Did it work? Do we do something different now?
> 
> Hello @IanMayo. No, I didn't try to cover that task. I realised that we had many unnecessary lines in your Postgres table definitions. I removed them but we still have the same "pepys" schema because I declared the schema name in inherited Base class.

Aah, I see - thanks @BarisSari

**Comment by IanMayo** [comment]
Hello @BarisSari & @robintw . After another day of development, the DB dev has produced a SQL query that runs quickly without the requirement for the index.

So, could you please modify the PR so we don't create the index, but we do include the tidying you identified?

**Comment by BarisSari** [comment]
It's ready, @IanMayo.

**Review by robintw — APPROVED** [review]
Great, thanks.

**Pull request merged**
