### PR TITLE
Hotfix/ Errors when loading incomplete .ini file (#303)

### LINKED ISSUE #303: Errors when loading incomplete .ini file
I created a `bare-bones` Pepys ini-file:
```
[database]
db_name = c:/sample_data/other_formats/pepys.sqlite
db_type = sqlite
```

But, Pepys-admin fell over when trying to read it:
```
C:\git\pepys-dev\pepys-import-develop\bin>CALL set_paths.bat
Successfully set paths for pepys-import
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\configparser.py", line 788, in get
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 916, in __getitem__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 908, in __missing__
KeyError: 'db_username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\git\pepys-dev\pepys-import-develop\pepys_admin\cli.py", line 3, in <module>
    from config import DB_HOST, DB_NAME, DB_PASSWORD, DB_PORT, DB_TYPE, DB_USERNAME
  File "C:\git\pepys-dev\pepys-import-develop\config.py", line 21, in <module>
    DB_USERNAME = config.get("database", "db_username")
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\configparser.py", line 791, in get
configparser.NoOptionError: No option 'db_username' in section: 'database'
Press any key to continue . . .
```

Pepys shouldn't fall over in these circumstances.  Maybe it doesn't need detailed, low-level handlers that allow for missing fields.  We _could_ have a higher level handler that just indicates it had trouble loading the ini file.  I don't feel strongly either way.

### PR DESCRIPTION
**Pull request by BarisSari**
Fixes #303 .

I tested to import all data from `sample_data` folder with the following configuration file:
```ini
[database]
db_name = pepys_test.sqlite
db_type = sqlite
[archive]
[local]

```

It worked without any problem.

### CODE REVIEW

**Comment by IanMayo** [comment]
@BarisSari - would it work if `[archive]` or `[local]` were missing?

**Comment by BarisSari** [comment]
> @BarisSari - would it work if `[archive]` or `[local]` were missing?

No, there are assertions which check the sections: database, archive, and local:

https://github.com/debrief/pepys-import/blob/bacd015198603f606470ee0d3e401fd6e404565c/config.py#L34

Do you want me to remove assertions?

**Comment by IanMayo** [comment]
Do we have defaults that are used when the individual fields are missing?

If we do, then we don't _need_ to fail if the section titles are missing - and we can remove the `assert` statements.

**Comment by BarisSari** [comment]
> Do we have defaults that are used when the individual fields are missing?
> 
> If we do, then we don't _need_ to fail if the section titles are missing - and we can remove the `assert` statements.

Yes, we do have defaults. I removed the assert statements:
https://github.com/debrief/pepys-import/pull/311/commits/97fb3e25510d1f29a1cbad5b32670aca0d9dc489

**Pull request merged**
