### PR TITLE
Partial Admin Shell is done with export functionality.

### PR DESCRIPTION
**Pull request by tahirs95**
Supports #53

### CODE REVIEW

**Comment by IanMayo** [comment]
@tahirs95 - in the fuzzy search, if we `escape` to cancel, you need to handle that.  It currently says: `Do you want to export None Datafile. (y/n)`

**Comment by IanMayo** [comment]
Once we've selected a file in the fuzzy search, we have the "y/n" choice. Could you switch it to "Y/n" (meaning press enter for Yes).

**Comment by IanMayo** [comment]
Thanks @tahirs95 .  But, could you also introduce another menu under `Initialise` that includes the next set of commands?
https://github.com/debrief/pepys-import/issues/53#user-content-initialise

**Comment by tahirs95** [comment]
> Thanks @tahirs95 . But, could you also introduce another menu under `Initialise` that includes the next set of commands?
> [#53 (comment)](https://github.com/debrief/pepys-import/issues/53#user-content-initialise)

Yeah! I will get it done.

**Comment by IanMayo** [comment]
@tahirs95 - the data_store has gone through a heavy refactoring in the last week or so.  I'd appreciate you updating your branch to match it.

Maybe you'll need to identify your changes to data_store.py, and re-apply them to an up-to-date copy from `develop`.

**Comment by tahirs95** [comment]
> @tahirs95 - the data_store has gone through a heavy refactoring in the last week or so. I'd appreciate you updating your branch to match it.
> 
> Maybe you'll need to identify your changes to data_store.py, and re-apply them to an up-to-date copy from `develop`.

Sure, I will look into it.

**Pull request merged**
