### PR TITLE
Write a basic script that parses the files in its' directory

### LINKED ISSUE #84: Create pepys_import command-line script
#44 says that we want to run a pepys_import batch script which will run a Python script to call the file processor with the current directory as an argument. We need to write that Python script.

### PR DESCRIPTION
**Pull request by BarisSari**
This PR aims to fix #84

### CODE REVIEW

**Comment by IanMayo** [comment]
One request please 

The script _may_ receive a file/folder path.

Could you use a path parameter if applied, or the current directory if not?

**Comment by BarisSari** [comment]
> One request please
> 
> The script _may_ receive a file/folder path.
> 
> Could you use a path parameter if applied, or the current directory if not?

Sure. I'm changing it.

**Comment by BarisSari** [comment]
> One request please
> 
> The script _may_ receive a file/folder path.
> 
> Could you use a path parameter if applied, or the current directory if not?

The script takes `--path XXXX` argument optionally.

**Comment by IanMayo** [comment]
Note: I've modified @BarisSari code to add the option for the database file to be specified. This lets us verify that the import worked.

**Pull request merged**
