### PR TITLE
Create filtered snapshots

### LINKED ISSUE #1025: Filtering snapshots prior to export
## :speech_balloon: Brief description of feature

The ability to apply one or more filters to database snapshots prior to exporting. 
Filters requested:
- Task/Operation
- Geographic area
- Timestamp range

## :bangbang: Business impact
Reduces issues with file size / disk space limitations when exporting data from a lower classification database and importing into a higher classification database

## :100: Acceptance criteria
- [ ] Can filter exports by task/operation
- [ ] Can filter exports by geographic area
- [ ] Can filter exports using a timestamp range

### PR DESCRIPTION
**Pull request by robintw**
## 🧰 Issue
Fixes #1025 

## 🚀 Overview: 
Adds the ability to export snapshots of the data that are filtered by various criteria such as time, wargame participation etc.

## 🔗 Link to preview (or screenshot, if relevant)
SnapshotExport

## 🤔 Reason: 
Users want to be able to filter exports.

## 🔨Work carried out:

- [x] Add `export_measurement_tables_filtered_by_X` functions
- [x] Add UI for for the user to provide start/end time, location etc
- [x] Add tests
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] Any database content changes (Create, Edit, Delete) are recorded in the Log/Changes tables
- [x] Any database schema changes are implemented via `alembic revision` [transitions](https://pepys-import.readthedocs.io/en/latest/database_migration.html#how-to-use-it-for-developers)
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by robintw** [comment]
This is ready for review now, I've invited you both to review.

I've been through the Codacy errors and fixed a load of them: the ones that are left are spurious errors (eg. using `==` to compare to None is required for SQLAlchemy filtering) so they don't need dealing with. I think we agreed just to ignore irrelevant Codacy errors.

**Comment by IanMayo** [comment]
@robintw - I've just played with the export snapshot of `tracstor` in the `codespace`.  

If I filter export by time, there is a delay between giving the filename and the prompt for start/end time.  Is this because it is exporting all the metadata, and asking for the measurment filter before exporting the measurements?

I _Think_ it would be better UX if we asked for the measurement filter before starting the export - then there is one long delay rather than two medium-length ones.

**Comment by robintw** [comment]
@IanMayo Yes that was the reason. I've changed that so that you select the filters first, then all the waiting happens together. I've also added some extra print statements to give a bit of feedback as to where it is in the process. For example:

```
--- Menu ---
(1) Create snapshot with Reference data
(2) Create snapshot with Reference data & Metadata
(3) Create snapshot with all data
(4) Create snapshot with all data, filtered by time
(5) Create snapshot with all data, filtered by location
(6) Create snapshot with all data, filtered by wargame
(7) Create snapshot with all data, filtered by serial
(8) Merge databases
(.) Back

(pepys-admin) (snapshot) 4
Start time (YYYY-MM-DD HH:MM:SS): 2000-01-01 00:00:00
End time (YYYY-MM-DD HH:MM:SS): 2004-01-01 00:00:00
SQLite database file to use: time7.db
Exporting reference and metadata tables
Exporting State measurement table
Exporting Contact measurement table
Exporting Comment measurement table
Exporting LogsHolding measurement table
Exporting Media measurement table
Exporting Activation measurement table
Exporting Geometry1 measurement table
Data successfully exported!
You can find it here: '/Users/robin/Documents/IanMayo/pepys-import/time7.db'.
```

**Comment by IanMayo** [comment]
@robintw - is it an option to provide a count of exported records?  That could give some early warning that the filters haven't worked as expected.

**Comment by robintw** [comment]
Good idea. I'll implement that.

**Comment by robintw** [comment]
Done (that was easier than I had thought):

```
Start time (YYYY-MM-DD HH:MM:SS): 2000-01-01 00:00:00
End time (YYYY-MM-DD HH:MM:SS): 2004-01-01 00:00:00
SQLite database file to use: time8.db
Exporting reference and metadata tables
Exported 5 entries from State
Exported 1 entries from Contact
Exported 6 entries from Comment
Exported 5 entries from Activation
Data successfully exported!
You can find it here: '/Users/robin/Documents/IanMayo/pepys-import/time8.db'.
```

**Comment by robintw** [comment]
Actually, hold off on merging this: looking at the coverage, I need to add some more tests for the UI interactions

**Comment by robintw** [comment]
UI tests added, and now code coverage is a lot better.

**Comment by IanMayo** [comment]
@robintw - for the analyst's specific use of this feature they will follow this workflow:
- Two PostGIS instances
- Export of all ref data, plus some filtered measurements from instance-1
- Merge that into instance of Pepys that just has the default metadata (instance-2)
- Import some more measurements (with supporting new metadata) into instance-1
- Export all of ref data, plus a filter for the new measurements from instance-1
- Import this new body of data into instance-2

Could you check the above works please? I'll find it a challenge to create the two PostGis instances - but I'm sure you can on your dev machine (well, `tracstor` and another local one).

**Comment by robintw** [comment]
Ok, I'll check that.

**Comment by robintw** [comment]
Just tested this with two Postgres databases, following the exact sequence you described, and it all worked fine. I've checked that the intermediate SQLite databases that were exported had the correct contents, and that the final merged database contains the new data.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
