### PR TITLE
Bulk import performance

### PR DESCRIPTION
**Pull request by BarisSari**
This PR has possible improvements to our import process. Yet, it might change once we decide to continue with a new approach.

### CODE REVIEW

**Comment by robintw** [comment]
I've been looking into this today (while also working on improving the efficiency of the highlighter code). You mentioned in #45 that when using `bulk_save_objects`, we don't store Log entities - is there any reason why we can't write a separate function to deal with inserting all of the Log entries once we've done the bulk insert of the State/Contact/whatever objects? (Ideally creating them in a list and then submitting them with a `bulk_save_objects` call, or even a `bulk_insert_mappings` call. I imagine that the overhead of having to create an insert a `Log` entry for each new State is slowing everything down quite a bit.

Also, looking at https://docs.sqlalchemy.org/en/13/orm/persistence_techniques.html#bulk-operations, it seems that grouping the objects by type will further speed things up - so calling `bulk_save_objects` once for all the State objects, then once for all the Contact objects etc. Obviously to do that we'd have to loop through the measurements and extract them into different lists - so I don't know if that overhead would actually make things worse - probably worth trying though.

**Comment by robintw** [comment]
Oh and I forgot to say - I _think_ that not expiring the Location field won't be too much of a problem. I actually wrote the Location class to be able to parse both the text representation and the full geographic-object representation of a Location - so it should work fine even if it's not expired (though expiring it is 'cleaner').

**Comment by BarisSari** [comment]
> I've been looking into this today (while also working on improving the efficiency of the highlighter code). You mentioned in #45 that when using `bulk_save_objects`, we don't store Log entities - is there any reason why we can't write a separate function to deal with inserting all of the Log entries once we've done the bulk insert of the State/Contact/whatever objects? (Ideally creating them in a list and then submitting them with a `bulk_save_objects` call, or even a `bulk_insert_mappings` call. I imagine that the overhead of having to create an insert a `Log` entry for each new State is slowing everything down quite a bit.
> 

I'm thinking to use `bulk_insert_mappings` call for log entries. I just wanted to play with the bulk-import operations without bothering with Log entries. That's why I haven't added it yet.

> Also, looking at https://docs.sqlalchemy.org/en/13/orm/persistence_techniques.html#bulk-operations, it seems that grouping the objects by type will further speed things up - so calling `bulk_save_objects` once for all the State objects, then once for all the Contact objects etc. Obviously to do that we'd have to loop through the measurements and extract them into different lists - so I don't know if that overhead would actually make things worse - probably worth trying though.

Actually, the measurements are already categorized according to their parser. So, Replay Importer has State objects only, Replay Contact Importer has Contact objects etc. And we are saving the objects for each parsers' items using `bulk_save_objects`. I tried to collect all measurements and insert them with one command and it made the performance worse. Therefore, `data_store.session.bulk_save_objects(objects)` is inside of the for loop.

**Comment by robintw** [comment]
That makes perfect sense @BarisSari

**Comment by BarisSari** [comment]
After switching to bulk-import(implemented in this PR)+Robin's highlighter improvements, I imported the zipped rep files(in #45) one more time. Performance increased by 13-14%.

**Comment by IanMayo** [comment]
@BarisSari - can you tell me why we've removed the mixins please?

**Pull request merged**
