### PR TITLE
Update to Developer Guide to include infor on pull requests

### PR DESCRIPTION
**Pull request by SamWilliams-dev**
## 🧰 Issue
Fixes 928

## 🚀 Overview: 

Documentation has been updated to provide more information on creating pull requests and git branching.

## 🤔 Reason: 

Team has grown, we should document the policy for branches & PRs.

## 🔨Work carried out:

Updated DeveloperGuide.rst to provide information about the pull request workflow.

- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [ ] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [ ] I have extended/updated the documentation in `\docs` folder
- [ ] Any database content changes (Create, Edit, Delete) are recorded in the Log/Changes tables
- [ ] Any database schema changes are implemented via `alembic revision` [transitions](https://pepys-import.readthedocs.io/en/latest/database_migration.html#how-to-use-it-for-developers)
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Review by robintw — APPROVED** [review]
Looks good to me, thanks Sam

**Review by mew-nsc — APPROVED** [review]
I'm happy. It's a good process clearly documented

**Review by robintw — APPROVED** [review]
Looks good, thanks Sam

**Review by IanMayo — APPROVED** [review]
Approving the words wot I wrote.

**Comment by SamWilliams-dev** [comment]
> Approving the words wot I wrote.

Unfortunately, I can't take credit for this one. Thanks for the documentation Ian!

**Pull request merged**
