### PR TITLE
Print all error messages in red

### LINKED ISSUE #706: Use RED for error messages
We should show error messages in red text.

If we don't get enough contrast for red shade in MS-Windows, we could experiment with just putting `ERROR` in red, or even just `!!` at the start of the line.

### PR DESCRIPTION
**Pull request by BarisSari**
## 🧰 Issue
Fixes #706 

## 🔨Work carried out:
- [x] Tests pass

## 🖥️ Screenshot
image
image
image
image
image

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by IanMayo** [comment]
This message wasn't in Red
image

Let me ask Celine if the numbered options should also be in Red.

**Comment by BarisSari** [comment]
> This message wasn't in Red

Thanks for catching it, @IanMayo. I'll print the message in red. Did you get an answer for numbered options?

**Comment by BarisSari** [comment]
This is how it looks when everything is printed in red:
image
and this is how it looks if only the message is printed in red: (We use this version in the PR for now)
image

**Review by IanMayo — APPROVED** [review]
Great, thanks @BarisSari

**Pull request merged**
