### PR TITLE
Add support for highlighting XML files

### LINKED ISSUE #647: Research supporting import highlighting in XML
Our import highlighting is really value for authors producing a new importer, or for an analyst who wants to double-check all the content got imported.

But, it doesn't work for XML, since we use an XML processing library.

This is a research task to consider how we could provide highlighting for the import.

I guess the options are:
1. extend our extraction code to support XML (though we'll need lots of code to handle the full range of XML :-( )
2. extend XML library to collect character index data necessary for producing highlighter 
3. use some new piece of code to "bind" the XML processing with our import highlighting

### PR DESCRIPTION
**Pull request by robintw**
## 🧰 Issue
Fixes #647 

## 🚀 Overview: 
Add custom XML parsing classes to allow recording extractions via highlighting on XML files, and update the GPX Importer to use these custom classes and do highlighting.

## 🔗 Link to preview (or screenshot, if relevant)
Example highlighting:
image

## 🤔 Reason: 
Highlighting was available for all file types except XML files, which was an anomaly - and having highlighting leads to far greater confidence from the clients that the importers are working properly.

## 🔨Work carried out:

- [x] Add custom XML parsing functions
- [x] Link custom XML parsing functions to HighlightedFile class using `record` method
- [x] Extend GPXImporter to use `record` calls from new parsing functions
- [x] Add tests for new custom XML parsing functions
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

## 📝 Developer Notes:
There are quite a few changes in this PR, but I think I've documented them fairly well - please ask if there are any questions about how the new XML stuff works.

This implementation will be slower than the implementation that didn't use highlighting, but the speed doesn't seem to be an issue. I've done a test with a GPX file containing ~1700 states and it is still processed within a few seconds. @IanMayo is checking how large the GPX files they usually process are, and we can do more investigation into speed later if they tell us they use enormous files regularly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Nice piece of work @robintw .  I'm particularly impressed by the documentation of the new parser:
https://github.com/debrief/pepys-import/pull/717/files#diff-f93c5c5ee9b330caf7555bb84ec3635ceef1c05410dc0df843cd369d8d37d77d

**Comment by IanMayo** [comment]
@robintw  - I tried to import a GPX file using the Binder.  I ran this command:
```
python -m pepys_import.cli --path tests/sample_data/track_files/gpx/test_land_track.gpx
```

But, the reports folder only contained the log, not the highlighted report.  Is highlighting switched off for GPX data?

**Review by BarisSari — APPROVED** [review]
Everything looks good, thanks @robintw. Out of curiosity, I have one question. It seems like we lost `sourceline` attribute of Element. Why did it happen? It seems like we still use the same `find`, `findall` methods with the original Element.

**Comment by robintw** [comment]
Ah yes, @BarisSari: we were originally using the `lxml` library, which is based on the ElementTree API but provides a slightly extended version of it. `lxml` provides a sourceline attribute, but the ElementTree API that we've now switched to using doesn't. It should be possible to try and work out a sourceline based on the character that we're already extracting, but it would require searching for all newlines every time we wanted it, and it might slow things down quite a bit. On the other hand, we should only need the sourceline when we're recording an error, so the slowdown might not be too bad.

@IanMayo would you like me to try implementing that? Thinking about it, knowing which line the error is on would be quite useful in fixing it!

**Comment by robintw** [comment]
@IanMayo It was a problem with Binder - I'd forgotten to update Binder to run on Python 3.8, and so some of the new code wasn't working properly. It now works fine on Binder - see screenshot below:

image

**Comment by IanMayo** [comment]
Yes Robin, it would be useful to know that the line number where an error occurred.

**Review by IanMayo — APPROVED** [review]
Yes, working fine, thanks @robintw  - though it took me a few minutes to recreate your output to HTML, when I could have just copied the way you did it. Duh.

**Review by IanMayo — CHANGES_REQUESTED** [review]
Changing to `request changes` to see if we can get the line number, for error reporting.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
