### PR TITLE
Make option validation dynamic for platform resolver

### LINKED ISSUE #607: You didn't select a valid option error
## Version
0.0.23

## 🐞 Description
While I'm testing to import a second file, I tried to select option 3 for platforms, which is offered on the menu. But it gives `You didn't select a valid option` error.

## ⚙️ Current behavior
When there is a created platform already, it is offered as a third option. But it's not possible to select it.

## ⚙️ Expected behavior
When a created platform is offered as a third option, we might select it as a platform.

## 🔢 Steps to Reproduce
1. Open Binder and run cells until this one:
`%xterm python -m pepys_import.cli --path tests/sample_data/track_files/gpx/gpx_1_0.gpx`
1. Run the cell and import gpx_1_0.gpx using command line resolver.
2. Change the cell to import gpx_1_1.gpx:
From: `%xterm python -m pepys_import.cli --path tests/sample_data/track_files/gpx/gpx_1_0.gpx`
To: `%xterm python -m pepys_import.cli --path tests/sample_data/track_files/gpx/gpx_1_1.gpx`
3. Run the cell
4. Select 3 and then 1, which will create a datafile.
5. Try to select 3, which will throw the error.

## 🖥️ Screenshots
image

```bash
$ python -m pepys_import.cli --path tests/sample_data/track_files/gpx/gpx_1_1.gpx
   @@@@ @@@@@        ______                      _                            _
 @@@@@ @@..@@@@      | ___ \                    (_)                          | |
  @@@     @@@@@@     | |_/ /__ _ __  _   _ ___   _ _ __ ___  _ __   ___  _ __| |_
  @@@     @@@@@@@@   |  __/ _ \ '_ \| | | / __| | | '_ ` _ \| '_ \ / _ \| '__| __|
 @@@@.     @@@@@@@   | | |  __/ |_) | |_| \__ \ | | | | | | | |_) | (_) | |  | |_
 @@ #@@ @   ...@@@@@ \_|  \___| .__/ \__, |___/ |_|_| |_| |_| .__/ \___/|_|   \__|
 @@   &        @@@@@            | |     __/ | ______          | |
Software Version :  0.0.23


Database Type :  sqlite
Database Name :  pepys_test.sqlite
Database Host :
-------------------------------------------------------------
==Before==
| Table name   |   Number of rows | Last item added            |
|--------------|------------------|----------------------------|
| States       |                5 | 2020-11-11 17:19:05.573809 |
| Contacts     |                0 | -                          |
| Comments     |                0 | -                          |
| Platforms    |                1 | 2020-11-11 17:18:43.833215 |

Ok, adding new datafile.
Please enter a name: gpx_1_1.gpx
Ok, please provide classification for new Datafile:
   1) Search an existing classification
   2) Add a new classification
   3) Public
   4) Public Sensitive
   5) Private
   6) Private UK/IE
   7) Very Private UK/IE
   8) Private UK/IE/FR
   9) Very Private UK/IE/FR
   .) Cancel import
 > 3
-------------------------------------------------------------
Input complete. About to create this datafile:
Name: gpx_1_1.gpx
Type: GPX
Classification: Public
Create this datafile?:
   1) Yes
   2) No, make further edits
   .) Cancel import
 > 1
GPX Importer working on gpx_1_1.gpx
  0%|                                                                         | 0/1 [00:00<?, ?it/s]Select a platform entry for NELSON:
   1) NELSON / )/_!->|*] / United Kingdom
   2) Search for existing platform
   3) Add a new platform, default name 'NELSON'
   .) Cancel import
 > 3
You didn't select a valid option
```

### PR DESCRIPTION
**Pull request by BarisSari**
## 🧰 Issue
Fixes #607 .

## 🤔 Reason: 
Solving the bug.

## 🔨Work carried out:
I changed the validation function for platform resolver. Then, I successfully created a platform using the third option which was not possible before.

- [x] Tests pass

## 🖥️ Screenshot
image

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks for that @BarisSari 

Celine is still getting up to speed on what we've got, and planning the guidance. I'm going to step in on her behalf regarding the UX. 

In the multiple-choice steps, there is great value in options keeping the same number.  For the first data-file, `Search for existing platform` is option 1.  But, for the second data-file it drops down to Option 2 (as in your screenshot).

When the options keep the same option number, the analysts have built up _muscle memory_ that allows them to _race_ through data entry.

So, could we adjust the menu so that the matching file drops to `Option 3`?  I know it's the _most likely_ option but the _muscle-memory_ only develops when the options are consistent.

**Review by IanMayo — CHANGES_REQUESTED** [review]
Thanks for that @BarisSari

Celine is still getting up to speed on what we've got, and planning the guidance. I'm going to step in on her behalf regarding the UX.

In the multiple-choice steps, there is great value in options keeping the same number. For the first data-file, Search for existing platform is option 1. But, for the second data-file it drops down to Option 2 (as in your screenshot).

When the options keep the same option number, the analysts have built up muscle memory that allows them to race through data entry.

So, could we adjust the menu so that the matching file drops to Option 3? I know it's the most likely option but the muscle-memory only develops when the options are consistent.

**Comment by BarisSari** [comment]
Sure, @IanMayo. I'm working on it.

**Comment by IanMayo** [comment]
Thanks @BarisSari  - could you update the screenshot please?

**Comment by BarisSari** [comment]
You're welcome, @IanMayo. I updated the screenshot.

**Comment by IanMayo** [comment]
Thanks @BarisSari .  

This is beyond the strict limits of the issue being fixed, but could you verify that this code can handle two instances of `Nelson` in the database?  The platform would still be called `Nelson` but would have a different identifier (or nation).

**Comment by BarisSari** [comment]
Yes, @IanMayo. the current code handles this situation. You can see example database entities below (only `identifier` is different for these `platforms`):

image

**Comment by IanMayo** [comment]
That's perfect, thanks Baris.

**Review by IanMayo — APPROVED** [review]

**Comment by BarisSari** [comment]
For your information, I think 4 Travis CI Builds were running at the same time and that's why benchmark tests failed for the last build.

**Review by robintw — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
