### PR TITLE
Change steps for Add new item

### LINKED ISSUE #701: Change steps for Add new item
Now that we _Skip_ "Search for existing sensor" if there aren't any, the "Add a new sensor" flickers between option 1) and 2).

If we changed the structure slightly, then "Add a new sensor" will always be on 1) and "Search for sensor" is either 2) or not present:
image

Yes, this will break some tests, and should be deferred until after the tutorial workshop.

### PR DESCRIPTION
**Pull request by BarisSari**
## 🧰 Issue
Fixes #701 

## 🚀 Overview: 
It changes the steps so that "Add a new sensor" will always be on 1) and "Search for sensor" is either 2) or not present.

## 🔨Work carried out:
- [x] Tests pass

## 🖥️ Screenshot
image

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

## 📝 Developer Notes:
I know that Ian said this should be deferred until after the tutorial workshop. But it didn't break many tests. I opened this PR and it is ready. So, it's Ian's call to merge it or not before the workshop.

### CODE REVIEW

**Comment by IanMayo** [comment]
@BarisSari - as we discussed in Slack, could you make the change for Platforms, too?

Note: we're expecting this change to break a number of tests, though I _suspect_ the fix will just require some swapping of `1` and `2` responses.

**Comment by BarisSari** [comment]
Sure, Ian. I'm going to change it now

**Review by robintw — APPROVED** [review]
Thanks @BarisSari, all looks good. This is the number of changes for the tests that I was expecting!

**Review by IanMayo — APPROVED** [review]
Great - thanks for catching the documentation updates, too.

**Pull request merged**
