### PR TITLE
Add check that database is at latest revision before merging

### PR DESCRIPTION
**Pull request by robintw**
This PR adds a check to the merging process to make sure that the slave database that is being merged into the main database is at the latest revision, and refuses to merge if it isn't. This is the latest revision according to the `latest_revisions.json` file that is present in the master installation - so this means that the slave SQLite database has to be at the latest version according to that installation - and therefore the schema should match the master Postgres database (as that will have been migrated when the installation was last upgraded).

@BarisSari: I'm going to write some tests for this tomorrow, but it'd be useful to use the 'out of date' SQLite database that you've created for tests in #540 as part of these. Therefore, I'll leave writing the last few of these tests until that PR is finished and merged, then we won't duplicate work.

### CODE REVIEW

**Comment by BarisSari** [comment]
> @BarisSari: I'm going to write some tests for this tomorrow, but it'd be useful to use the 'out of date' SQLite database that you've created for tests in #540 as part of these. Therefore, I'll leave writing the last few of these tests until that PR is finished and merged, then we won't duplicate work.

I've added an old SQLite database to that PR, @robintw . It's waiting for your review.

**Comment by robintw** [comment]
Thanks @Baris. I've added tests using that database here, and I think this PR is ready for review now.

**Comment by IanMayo** [comment]
Thanks @robintw - it looks just right. You need to mark it as `Ready for review`.

**Comment by robintw** [comment]
Fixed now @IanMayo, sorry about that.

**Pull request merged**
