### PR TITLE
Change color of prompt lines

### LINKED ISSUE #646: Put prompt/Call to action text in another color.
## 🐞 Overview
We're currently formatting the prompt lines in **bold**.  They would be even easier to spot if they were in a different color.

Right now (*), the backdrop in MS-Windows & Jupyter is black.  So, for this issue the prompt should be light-blue.

(*) @robintw is experimenting with switching to a white background, which would encourage us to use a darker color for the prompt text.  But, any such change should only impact on the method that provides the formatted prompt text.

## 🔗 Feature
supports #595 

## 🔢 Acceptance criteria
* [ ] Prompts in `Pepys-import` shaded in light blue in local terminal
* [ ] Prompts in `Pepys-import` shaded in light blue in Jupyter Notebook

### PR DESCRIPTION
**Pull request by BarisSari**
## 🧰 Issue
Fixes #646

## 🔨Work carried out:
- [x] Tests pass

## 🖥️ Screenshot
Going to be added.

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by IanMayo** [comment]
@BarisSari - is this ready for review?

**Comment by BarisSari** [comment]
Yes, Ian. It's ready

**Review by IanMayo — APPROVED** [review]
Oh, I didn't realise so little code had changed 🤣

**Review by robintw — APPROVED** [review]

**Comment by BarisSari** [comment]
Sorry, I couldn't convert mark it "ready for review" when I was on mobile.

> Oh, I didn't realise so little code had changed 🤣

Yes, I think it means that we are in the correct way to format our prompts 😄

**Comment by IanMayo** [comment]
Yes, well we've got enough in there for Celine to review it.

**Pull request merged**
