### PR TITLE
Add 'Duplicate Serial' functionality

### LINKED ISSUE #857: Duplicate serial
Issue renamed, to use simpler implementation that wouldn't require database changes.

**Update:**

I've just checked with analysts, and `Duplicate task` would be a satisfactory solution to this issue. I propose we duplicate all fields, but append `Copy xx` at the end of the serial number.  Hopefully there is existing logic to handle the sequential (`Copy 1, Copy 2`etc) values.

If we have chance, it would be good to deliver `Duplicate task` in the near-term since they will be able to take immediate advantage of it.

### Former strategy

Groups of units is not required for May 2021.

In a wargame, a group of ships/platforms could be grouped into a Task Group.    This group of ships will be act in many serials, largely without any changes.

It's currently cumbersome to repeatedly add them one-by-one to the serials they take part in.

We need a further discovery stage on this to determine if the composition of a task group changes, do we need to modify the serials?  

One solution would be for Wargame Participants to have a `TaskGroup` field. This _could_ be free text.  When we add a participant to a serial, the listing offers unique partiicpants, and the names of any declared task groups.

Or we could swap the free text for an optional entry from the Task Group Names table.

An alternate strategy that could solve the re-typing issue could be a `Duplicate task` button.

### PR DESCRIPTION
**Pull request by robintw**
## 🧰 Issue
Fixes #857 

## 🚀 Overview: 
Adds a 'Duplicate Serial' button in the Tasks GUI, which duplicates the current serial, and gives it a sensible name (`XXX Copy`, `XXX Copy 2` etc)

## 🔗 Link to preview (or screenshot, if relevant)
image

## 🤔 Reason: 
Makes it easier for users to create lots of similar serials

## 🔨Work carried out:

- [x] Add Duplicate Serial button, plus handler function to do the duplication
- [x] Add utility function to copy a SQLAlchemy object
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] Any database content changes (Create, Edit, Delete) are recorded in the Log/Changes tables
- [x] Any database schema changes are implemented via `alembic revision` [transitions](https://pepys-import.readthedocs.io/en/latest/database_migration.html#how-to-use-it-for-developers)
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by robintw** [comment]
@IanMayo I've implemented the Duplicate Serial functionality here. I've tested it, and haven't found any bugs yet - but there may well be some to find. Please download a release and have a go and let me know if you run into any problems.

If you can't find any problems then I'm happy for this to be merged.

**Comment by IanMayo** [comment]
Thanks @robintw  - will do.

Should I be able to see `Duplicate serial` in the preview image?

**Comment by robintw** [comment]
Ah, I uploaded the wrong screenshot - sorry! Here's a screenshot of viewing a Serial. The button appears next to the 'delete' button, and only when viewing serials:

image

**Comment by IanMayo** [comment]
This isn't related to <Duplicate serial> but I go this error on deleting a serial participant. There were two, I deleted one, and got this error:
```
pepys-admin) 9
Initialising GUI and loading tasks and platforms...

Unhandled exception in event loop:
  File "asyncio\events.py", line 81, in _run
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\input\win32.py", line 536, in ready
    callback()
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\application\application.py", line 691, in read_from_input
    self.key_processor.process_keys()
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\key_binding\key_processor.py", line 274, in process_keys
    self._process_coroutine.send(key_press)
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\key_binding\key_processor.py", line 186, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\key_binding\key_processor.py", line 329, in _call_handler
    handler.call(event)
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\key_binding\key_bindings.py", line 102, in call
    result = self.handler(event)
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\key_binding\bindings\mouse.py", line 145, in _mouse
    handler(MouseEvent(position=Point(x=x, y=y), event_type=event_type))
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\layout\containers.py", line 1860, in mouse_handler
    result = self.content.mouse_handler(
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\layout\controls.py", line 472, in mouse_handler
    return handler(mouse_event)
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\python\Lib\site-packages\prompt_toolkit\widgets\base.py", line 433, in handler
    self.handler()
  File "Z:\MacDownloads\pepys_import-20210427-duplicate-serial-fb4966f\pepys_admin\maintenance\widgets\participants_widget.py", line 410, in handle_delete_button
    participant = self.participants[self.combo_box.selected_entry]

Exception list index out of range
Press ENTER to continue...
```

**Comment by IanMayo** [comment]
Aah, I think I can reproduce it.  I've just tried again.  After I delete a serial participant, no participant is selected. If I then press Delete, I get the error.

**Comment by robintw** [comment]
The bug you reported here has been fixed in #863. Could you merge this first, then #863.

**Comment by IanMayo** [comment]
Closing. The changes from this PR are now all in develop.

**Pull request closed without merging**
