### PR TITLE
Add Serials.include_in_timeline field, and update Tasks GUI to be able to edit it

### PR DESCRIPTION
**Pull request by robintw**
## 🧰 Issue
#854

## 🚀 Overview: 
Add a new field to the Serials table, called `include_in_timeline` and update the Tasks GUI so it can be edited.

## 🔗 Link to preview (or screenshot, if relevant)
image

## 🤔 Reason: 
So the clients can easily choose which Serials to include in the timeline display.

## 🔨Work carried out:

- [x] Add new field to database
- [x] Add database migration
- [x] Update GUI to display and store new field
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] Any database content changes (Create, Edit, Delete) are recorded in the Log/Changes tables
- [x] Any database schema changes are implemented via `alembic revision` [transitions](https://pepys-import.readthedocs.io/en/latest/database_migration.html#how-to-use-it-for-developers)
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by IanMayo** [comment]
@robintw  - if it doesn't mean you battling with prompt_toolkit, could we follow the label: control layout like in the other fields please?

If it does mean battling, then I'm happy to accept control: label.

**Comment by robintw** [comment]
@IanMayo I had intended to comment that it was going to be very tricky to do that, because I'd have to create a variant of the Checkbox widget. However, I just realised there is an obvious alternative way to do it: set the text on the Checkbox to be an empty string, and then manually add a Label widget on the left-hand side.

I've now implemented that, plus an addition to the Maintenance GUI so that it can support filtering by boolean fields, and I think this is ready for review now.

**Comment by IanMayo** [comment]
I've had an issue while running the migration, `Maintain tasks` fails to open without the migration being performed. I'll have to talk to @arunlal-v  about it.
```
(pepys-admin) 5
Your database schema is going to be updated. Are you sure to continue? (y/N) y
Alembic migration command running, see output below.
len(table_names)=40
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade ff66e16c21ef -> f17f01e2f2c5, Add include_in_timeline field
Exception details: (psycopg2.errors.InsufficientPrivilege) must be owner of table Serials

[SQL: ALTER TABLE pepys."Serials" ADD COLUMN include_in_timeline BOOLEAN NOT NULL]
(Background on this error at: http://sqlalche.me/e/13/f405)

ERROR: Alembic error when migrating the database!
```

**Comment by IanMayo** [comment]
@robintw - tested fine in the `Maintain Tasks` view.  But, in `Maintenance tools` I get this error when trying to edit one or  two serials:
image

(no rush)

**Comment by robintw** [comment]
I think that is fixed now - I can't seem to reproduce the error anymore anyway. Can you have a go and see if you think it is all fixed?

If so, then I'm happy for this to be merged.

**Comment by IanMayo** [comment]
Still getting issue, @robintw 

Have checked build date in title, just to be sure.

Steps to reproduce:
1. Enter pepys-admin
2. Enter Maintenance
3. Select `Serials`
4. Select both serials
5. Select `Edit values` -> Exception thrown

**Comment by IanMayo** [comment]
Another issue.  Steps:
1. Enter pepys_admin
2. Enter maintenance
3. Select table `Serial Participants`
4. Select <ctrl-f> to select fields, exception thrown:

image

**Comment by robintw** [comment]
I've realised why I was getting confused here - there is another PR that needs to be merged before this one, and that other PR includes the fixes for all these issues. The PR is here: https://github.com/debrief/pepys-import/pull/852. I just need to do one more minor change to switch to just using commas for displaying lists, and then that can be merged, and then this can be merged too.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
