### PR TITLE
Add an end-to-end system test using pexpect

### PR DESCRIPTION
**Pull request by robintw**
## 🧰 Issue
Contributes to fixing #927

## 🚀 Overview: 
Adds a test for doing an end-to-end test of the import CLI using the `pexpect` module (based on the Unix `expect` program). This is a way of running a program (in this case, the import CLI) and sending keypresses to it, and 'expecting' certain output from it. By combining these 'sends' and 'expects', we can automate the interaction with the UI. For example, code like this:

```
child.expect_exact("> ")
child.sendline("2")
```

expects a prompt from the program, and responds with `2` (followed by Enter), and 

```
child.expect_exact("Files got processed: 1 times")
```
expects to see that output from the program.

Currently this does not run on Windows, so there is code to skip this test on Windows.

## 🤔 Reason: 
Better testing

## 🔨Work carried out:

- [x] Add pexpect-based test
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] Any database content changes (Create, Edit, Delete) are recorded in the Log/Changes tables
- [x] Any database schema changes are implemented via `alembic revision` [transitions](https://pepys-import.readthedocs.io/en/latest/database_migration.html#how-to-use-it-for-developers)
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by robintw** [comment]
@IanMayo You weren't in standup when I discussed this earlier. Do you think this is a sensible approach? If so, I'll go ahead with trying to get it working on Windows.

**Comment by IanMayo** [comment]
> @IanMayo You weren't in standup when I discussed this earlier. Do you think this is a sensible approach? If so, I'll go ahead with trying to get it working on Windows.

Ooh, it's a shame I missed the discussion.

This does tick the box of running Pepys _from the outside_, , but I _imagined_ something that was closer to plain English.  Then _roughly_ the same content could be used manually by a person, or automatically as part of CI.

I also think we need to consider where we invest effort in the System Tests.  If the greatest value comes from testing Pepys Admin (it's heavy GUI nature means it has less unit testing), but `pexpect` can't help us there, then I think we should consider another strategy.

Maybe we should discuss it with @mew-nsc & @SamWilliams-dev  either in the next standup, or a specific call.

**Comment by IanMayo** [comment]
I think it may be worth discussing this at the next standup.  We do an import in the System Test.  I have a minor worry that this may be a bit fragile.  Hmm, but if it means the full import cycle is covered in every set of unit tests, that could be a positive benefit.

**Comment by robintw** [comment]
Yes we can chat in standup. My personal view is that it's worth including at the moment, and if it proves to be really fragile then it can be removed in future. It does do a full independent end-to-end check which we don't have elsewhere - so I think it could be useful.

**Review by IanMayo — APPROVED** [review]
Yes - this is a valuable end-to-end test that would bring value to our automated unit tests by being run so regularly/frequently.

**Pull request merged**
