### PR TITLE
Add validation in tasks GUI to check start time is before end time

### LINKED ISSUE #1034: Timeline viewer - reporting start not before end
The webpage for the timeline viewer was reporting that the start date wasn't before the end date.

I set the date as 12/05/2021 - 12/05/2021.  I knew there were around 5 serials happening that day - with participants assigned to the serials.

Instead of the coverage diagrams, a red panel was shown, titled `Error Querying database`.

Then:
```
Traceback:
pepys_timeline\db.py line 35 in get_query_result curs.execute(query, vars)
psycopg2.errors.DataException: range lower bound must be less than or
equal to range upper bound
CONTEXT PL/pgsql function pepys.dashboard_stats(text.text) line at RETURN QUERY
```

In Chrome I opened the network tab, and viewed the query params for `from_date` and `to_date`.  They had the correct values, in the correct order.

The returned data looked valid.

I then looked at the network call for dashboard_stats. These fields were provided:
```
range_types: "G", "C"
serial_participants:  70 entries. start and end fields are in the correct order.
```
But, the call returned the above error.

### PR DESCRIPTION
**Pull request by robintw**
## 🧰 Issue
Fixes #1034 

## 🚀 Overview: 
Adds validation to the Tasks GUI to check that the start time of a Wargame/Serial/Participant is not after the end time.

## 🔗 Link to preview (or screenshot, if relevant)
image
and
image

## 🤔 Reason: 
Stop the user from creating invalid data.

## 🔨Work carried out:

- [x] Add validation checks
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] Any database content changes (Create, Edit, Delete) are recorded in the Log/Changes tables
- [x] Any database schema changes are implemented via `alembic revision` [transitions](https://pepys-import.readthedocs.io/en/latest/database_migration.html#how-to-use-it-for-developers)
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by IanMayo** [comment]
I just tried to test this in the `CodeSpace`. I had an empty database that I had to initialise. Then I went into `Maintain Tasks`. As I was adding the first `Wargame-series` I got this error:
image

**Comment by robintw** [comment]
Did you mean to close this @IanMayo?

I'll work on a fix for that bug shortly.

**Comment by robintw** [comment]
Fixed now.

**Comment by IanMayo** [comment]
Sorry - my mistake.

**Review by IanMayo — APPROVED** [review]
Logic looks correct

**Review by IanMayo — APPROVED** [review]
Tested.  Check happens for both Serials and Wargames.

**Pull request merged**
