### PR TITLE
Fix Readme Missing

### LINKED ISSUE #29: Docs = readme is missing
We've got the source-code comments included in the output: https://pepys-import.readthedocs.io/en/latest/

But we aren't currently including the README in the output.

It's not present for a local build or a remote build.

I suspect `Ian` has mangled the docs folder, I'm sure `readme` used to be in the read-the-docs content.

### LINKED ISSUE #38: Switch README from .md to .rst
It _looks like_ our Sphinx doc generation (including read-the-docs) favours `.rst` over `.md`

Could you please rewrite our repo in `.rst` and rename the page to `README.rst, please?

The the automatic docs should be formatted more nicely.

### PR DESCRIPTION
**Pull request by BarisSari**
Fixes #29 
Fixes #38 

I added **converted** file, README.rst to the index.

### CODE REVIEW

**Comment by IanMayo** [comment]
Does it work if you do a local `make docs`?

**Comment by BarisSari** [comment]
> Does it work if you do a local `make docs`?

It adds readme but not formatted:

Screenshot from 2019-11-11 12-46-15

**Comment by BarisSari** [comment]
I converted README.md to README.rst and added issue link to the first message. It works fine when `make docs` run right now.

**Comment by IanMayo** [comment]
I've done some playing.

The docs opened with the repo README, but there wasn't a way of getting back to this content from the contents listing.

I've also done some minor refactoring.

**Pull request merged**
