### PR TITLE
Add overall exception handlers to catch SQLAlchemy exceptions

### PR DESCRIPTION
**Pull request by robintw**
Adds exception handlers at a high level around both the pepys-import and pepys-admin CLIs, to catch a SQLAlchemy ProgrammingError, which occurs when the SQL doesn't make sense - eg. when fields are missing in the database.

Gives a sensible error message - but let me know if you want to reword it.

### CODE REVIEW

**Comment by IanMayo** [comment]
@robintw  - do we have a way of writing tests for this?

I _guess_ we could run an import on an in-memory database - which will initialise it.  Then we can check it robustly handles:
* the database is missing a field that is present in the SQLAlchemy schema
* the database has a field that is of a different type to the SQLAlchemy schema

**Comment by robintw** [comment]
I don't understand why the patch coverage is showing so low here: it seems to be picking up some issues with coverage in a file that I didn't even edit (but that maybe came in through a merge?). Anyway, in my opinion it can be probably be ignored.

**Comment by IanMayo** [comment]
I've just tried to run `pepys_admin` using a file (attached) that is missing the new `sensors.privacy_id` field.  When I try to do `status` from `pepys_admin` the app crashes, and I get this error:
```
-------------------------------------------------------------
--- Menu ---
(1) Initialise/Clear
(2) Status
(3) Export
(4) Export by Platform and sensor
(0) Exit

(pepys-admin) 2
## Measurements
| Table name   |   Number of rows | Last item added            |
|--------------|------------------|----------------------------|
| States       |            12209 | 2020-04-04 13:05:58.891892 |
| Contacts     |               15 | 2020-04-04 13:05:53.675938 |
| Activations  |                0 | -                          |
| LogsHoldings |                0 | -                          |
| Comments     |                7 | 2020-04-04 13:05:52.894812 |
| Geometries   |                0 | -                          |
| Media        |                0 | -                          |


Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cmd.py", line 214, in onecmd
AttributeError: 'AdminShell' object has no attribute 'do_2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: Sensors.privacy_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\git\pepys-import\pepys_admin\cli.py", line 54, in <module>
    main()
  File "C:\git\pepys-import\pepys_admin\cli.py", line 42, in main
    AdminShell(data_store, args.path).cmdloop()
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cmd.py", line 138, in cmdloop
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cmd.py", line 216, in onecmd
  File "C:\git\pepys-import\pepys_admin\admin_cli.py", line 177, in default
    self.aliases[command]()
  File "C:\git\pepys-import\pepys_admin\admin_cli.py", line 160, in do_status
    metadata_summary = self.data_store.get_status(report_metadata=True)
  File "C:\git\pepys-import\pepys_import\core\store\data_store.py", line 823, in get_status
    summary = TableSummary(self.session, table_object)
  File "C:\git\pepys-import\pepys_import\core\store\table_summary.py", line 21, in __init__
    self.table_summary()
  File "C:\git\pepys-import\pepys_import\core\store\table_summary.py", line 24, in table_summary
    number_of_rows = self.session.query(self.table).count()
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3605, in count
    return self.from_self(col).scalar()
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3330, in scalar
    ret = self.one()
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3300, in one
    ret = self.one_or_none()
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3269, in one_or_none
    ret = list(self)
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3367, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\git\pepys-import\python\Lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: Sensors.privacy_id
[SQL: SELECT count(*) AS count_1
FROM (SELECT "Sensors".sensor_id AS "Sensors_sensor_id", "Sensors".name AS "Sensors_name", "Sensors".sensor_type_id AS "Sensors_sensor_type_id", "Sensors".host AS "Sensors_host", "Sensors".privacy_id AS "Sensors_privacy_id", "Sensors".created_date AS "Sensors_created_date"
FROM "Sensors") AS anon_1]
(Background on this error at: http://sqlalche.me/e/e3q8)
Press any key to continue . . .

```

Offending file:
[pepys.zip](https://github.com/debrief/pepys-import/files/4457043/pepys.zip)

**Comment by robintw** [comment]
I can't seem to reproduce this problem with the file you attached - it just says that the database tables aren't found. I'll add a separate issue about that problem, because I can't seem to work out what's causing it.

As for the actual error you experienced: I've fixed that now - but it seems like its difficult to add tests that use the highest level of the admin CLI (current tests are for individual parts of it), so I think it'll be hard to test this for the admin CLI.

**Comment by IanMayo** [comment]
> database tables aren't found.  

Is there a chance you're pointing `pepys_admin` at the wrong database? When I look at it with `DB Browser for SQLite` I see all tables, and lots of data 29 platforms, for example.   I can see that `privacy_id` is missing from `sensors`.

**Comment by IanMayo** [comment]
The new version tidily caught the exception in my dodgy file.

**Comment by robintw** [comment]
Tests now implemented for both import and admin CLIs.

**Pull request merged**
