### PR TITLE
Add interactive demos of PRs

### PR DESCRIPTION
**Pull request by robintw**
##  🧰 Issue
#597 

## 🚀 Overview: 
Added a Github Actions workflow that automatically builds a Binder image for the PR on every commit, if the PR has the `interactive_review` label. Once it's built it adds a comment with a link to a Jupyter notebook server running in the `demos` folder.

## 🤔 Reason: 
Gives the opportunity for less-technical users, such as the clients, or @clenoble, to easily test PRs containing new features in a live notebook with real UI (better than just seeing an animated screenshot).

## 🔨Work carried out:

- [x] Added Github Action and tested

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by IanMayo** [comment]
@robintw  - having a play. The auto-generated link above misses the first part of the filename in the destination URL.

**Comment by robintw** [comment]
Yes I'm aware - it's not quite ready for playing yet...!

**Comment by IanMayo** [comment]
Sure, ok - my enthusiasm for the solution was because of how it would help the review of other PRs.

**Comment by robintw** [comment]
I think this is ready for review now. Probably best to review the code (well, YAML config) and then merge and create a new PR to check that it behaves as it should. I can do this check once this has been merged.

@BarisSari I tried to use git rebase to squash the multiple commits that I had to create to get various bits of GH Actions working, but it seemed to fail each time, and I'm not sure what's going on. If you're able to do any squashing then feel free - I think you're probably more experienced at it than me.

**Comment by IanMayo** [comment]
@robintw  - will it only apply for new PRs?

I _guess_ if I update an existing PR it will introduce the new action(s).

**Comment by IanMayo** [comment]
> I think this is ready for review now.

Marking as `Ready for review`

**Comment by BarisSari** [comment]
Hello @robintw. I'll give it a try to squash some commits. Then, I'm going to approve the PR.

**Review by IanMayo — APPROVED** [review]
> then merge and create a new PR to check that it behaves as it should

Yes, let's get it up & running, and learn about it.

**Review by BarisSari — APPROVED** [review]
Looks great, thanks @robintw.

**Pull request merged**
