### PR TITLE
Maintenance GUI - Phase 3

### PR DESCRIPTION
**Pull request by robintw**
## 🧰 Issue
#600 

## 🚀 Overview: 
Phase 3 of the Maintenance GUI, as described at https://docs.google.com/drawings/d/1WopPwQoUFGYnEZCQeglWsBalH7ye6ECWh2TyI0r7tfY/edit - specifically, adding the Split Platforms action.

## 🔗 Link to preview (or screenshot, if relevant)
MaintenanceGUI_2021-02-23

## 🤔 Reason: 
Ease maintenance

## 🔨Work carried out:

- [x] Add Split Platform action, including confirmation dialog (so nothing happens if the user activates the action by accident)
- [x] Add `set_percentage` calls inside the split function, to give progress bar output
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [x] I have extended/updated the documentation in `\docs` folder
- [x] Any database changes are recorded in the Log/Changes tables
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Review by BarisSari — APPROVED** [review]
Looks good, thanks @robintw.

**Comment by IanMayo** [comment]
I've just collated a database, and performed a split. 

The split platforms are using today's date as their identifier.  This doesn't help organise/manage them.  The intention was that the identifier would take the date/time of the first `Measurement` for the datafile used for the splitting decision.  With the measurement name in the new Platform title, it's possible to merge back split platforms that had data on consecutive days.

image

I'll also attach copies of the SQLite database used before and after the split.
[databases.zip](https://github.com/debrief/pepys-import/files/6035206/databases.zip)

This feedback is almost certainly for @BarisSari rather than @robintw .

**Comment by IanMayo** [comment]
I have another observation.  After the `split`, we have the same number of sensors.  But, where `Platform1` has `GPS` for 3 datafiles, this will be split into 3 `Platforms`, each with a `GPS` sensor.

The attached spreadsheet summarises the data before/after the split. In the `before` states I've shaded the `GPS` on `Callsign 1` in green. I've shaded the 5 datafiles that contain data for this sensor in different shades.  After the split, these states should be split across the 5 new platforms.  Well, 5 sensors on 5 platforms.
[before after split.xlsx.zip](https://github.com/debrief/pepys-import/files/6035416/before.after.split.xlsx.zip)

Another clue to what's happening is that both before and after the split there are the same number of sensors.  I think the existing `Callsign 1` - `GPS` been assigned to the new `Callsign 1` platform, and all original `States` remain assigned to this sensor.

**Comment by BarisSari** [comment]
Hello @IanMayo. I'll look at the issues tomorrow morning.

**Review by IanMayo — APPROVED** [review]
Have tested this, before and after the `split-platforms` hotfix.

It now works satisfactorily.

**Review by BarisSari — APPROVED** [review]

**Pull request merged**
