### PR TITLE
[wip] Start using ConfigOptions table in timeline

### LINKED ISSUE #884: Display message of the day
The users are looking forward to the timeline displaying a message of the day.

There were thoughts that this could show issues to focus on, but the client lead was keen to see `Manager of the day: Daisy`.

We still need to work on layout/design for the timeline page, but a large central text box occupying 50% of width would be a start.

The table will be implemented in this issue: https://github.com/debrief/pepys-import/issues/871

It is expected that a call to the options be made just after the existing update cycle.

### PR DESCRIPTION
**Pull request by krsnik93**
## 🧰 Issue

Fixes #884 

## 🚀 Overview: 

Previous PR for the same issue introduced the message of the day block with a placeholder message. In this PR, we start using the `pepys."ConfigOptions"` table to get the real message and display it.

## 🤔 Reason: 

Previous PR was only able to display the placeholder message of the day.

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR, adding `interactive_review` if reviewers will need to see UI
- [ ] I have extended/updated the documentation in `\docs` folder
- [ ] Any database content changes (Create, Edit, Delete) are recorded in the Log/Changes tables
- [ ] Any database schema changes are implemented via `alembic revision` [transitions](https://pepys-import.readthedocs.io/en/latest/database_migration.html#how-to-use-it-for-developers)
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by IanMayo** [comment]
> fonts , spacing, colours

I'm happy to focus on the tech for now. it's all quite legible

**Comment by IanMayo** [comment]
@krsnik93 - is this ready to go?

**Comment by krsnik93** [comment]
@IanMayo All good from my side!

**Comment by IanMayo** [comment]
> @IanMayo All good from my side!

thanks - I'd been holding it back, since it still had `[WIP]` in the title ;-)

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
