### PR TITLE
Make prompt text bold, add new line before printing menu

### LINKED ISSUE #615: Layout issue in loading file process
## 🐞 Description
After confirming the creation of a new datafile, the GPX importer progress bar and the instruction "Select a platform entry for...:" are on the same line

## ⚙️ Current behavior
With large width of the terminal, the layout is very confusing for the user.

## ⚙️ Expected behavior
"Select a platform entry for..." should be on its own separate line.
I also recommend to highlight (bold) the instruction.

## 🔢 Steps to Reproduce

1. Load a file in Pepys
2. Enlarge terminal
3. Go through the import process until Select a platform entry

## 🖥️ Screenshots
image (2)

### PR DESCRIPTION
**Pull request by BarisSari**
## 🧰 Issue
Fixes #615 
## 🔨Work carried out:

- [x] Format text function added. It makes given text bold.
- [x] All prompt's called with new _format_text()_ function. So, all menus are **bold** now.
- [x] Tests pass

## 🖥️ Screenshot (UPDATED)
image

image
image

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.

### CODE REVIEW

**Comment by IanMayo** [comment]
One suggestion please @BarisSari ,
could you rename `formatText()` to `formatCommand()` ?

It seems valid to name the type of text that is being formatted, since we will _probably_ soon have formatting for context-sensitive guidance.

**Comment by BarisSari** [comment]
Sure, @IanMayo. I renamed the function: https://github.com/debrief/pepys-import/pull/633/commits/7d822fb73241db11e5175157f46f11cceaf63745

**Review by IanMayo — APPROVED** [review]
Great, thanks.

**Comment by IanMayo** [comment]
@BarisSari - feedback from @clenoble 

Just the questions in bold, please:
image

**Comment by BarisSari** [comment]
Okay, I might need to change the styling to HTML for that. I'll try and let you know.

**Comment by IanMayo** [comment]
So @BarisSari ,  in the screenshot for this PR, the corrected version will only have `Create this datafile?` and `Select a platform entry for SENSOR:` in bold.

**Comment by IanMayo** [comment]
I've added @robintw `interactive_review` label.  When I scrolled back down to the bottom, `Interactive PRs` had restarted.

**Comment by BarisSari** [comment]
> So @BarisSari , in the screenshot for this PR, the corrected version will only have `Create this datafile?` and `Select a platform entry for SENSOR:` in bold.

Okay, thanks @IanMayo. I'll make changes tomorrow.

**Comment by IanMayo** [comment]
Maybe it's a shortcoming in xterm, but I don't get the bold font in Jupyter:

image

**Comment by IanMayo** [comment]
But, bold text is shown correctly in MACOS terminal:

**Review by IanMayo — CHANGES_REQUESTED** [review]
The Binder worked perfectly (even if xterm doesn't show bold font :-( ).

But, Celine has asked that only the specific question be written in bold.

**Comment by robintw** [comment]
I've updated our fork of the `notebook_xterm` Jupyter plugin that lets us use terminals in the notebook, and it now supports bold text. Next time you push something to this PR, the Binder notebook will rebuild and use the latest version of notebook_xterm, and you should be able to see the bold text in the terminal @IanMayo. (I've tested it locally and it works, so should be fine on Binder).

**Comment by IanMayo** [comment]
Formatting looking fine - only the prompt is bold:
image

But, @robintw  - it _appears_ that we're not getting bold in the new xterm (see below).  _Maybe_ we need to wait for a new PR.
image

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
